
--  Basic data quality checks on ONLINE_RETAIL_MASTER_TABLE

-- Total rows in the dataset
SELECT COUNT(*) AS TOTAL_ROWS
FROM ONLINE_RETAIL_MASTER_TABLE;

--  Total unique invoices
SELECT COUNT(DISTINCT INVOICENO) AS UNIQUE_INVOICES
FROM ONLINE_RETAIL_MASTER_TABLE;

--  Total cancelled orders
SELECT COUNT(*) AS CANCELLED_ORDERS
FROM ONLINE_RETAIL_MASTER_TABLE
WHERE INVOICENO LIKE 'C%';

--  Check for NULL or missing values in key columns
SELECT *
FROM ONLINE_RETAIL_MASTER_TABLE
WHERE INVOICENO IS NULL
   OR STOCKCODE IS NULL
   OR DESCRIPTION IS NULL
   OR QUANTITY IS NULL
   OR INVOICEDATE IS NULL
   OR UNITPRICE IS NULL
   OR CUSTOMERID IS NULL
   OR COUNTRY IS NULL;

--  Trimmed strings check (remove leading/trailing spaces)
SELECT *
FROM ONLINE_RETAIL_MASTER_TABLE
WHERE TRIM(INVOICENO) <> INVOICENO
   OR TRIM(STOCKCODE) <> STOCKCODE
   OR TRIM(DESCRIPTION) <> DESCRIPTION
   OR TRIM(COUNTRY) <> COUNTRY;

-- Check for duplicate invoices with same customer
SELECT INVOICENO, CUSTOMERID, COUNT(*) AS DUPLICATE_COUNT
FROM ONLINE_RETAIL_MASTER_TABLE
GROUP BY INVOICENO, CUSTOMERID
HAVING COUNT(*) > 1
ORDER BY DUPLICATE_COUNT DESC;

--  Check for negative quantity or unit price (data errors)
SELECT *
FROM ONLINE_RETAIL_MASTER_TABLE
WHERE QUANTITY < 0
   OR UNITPRICE < 0;

SELECT 
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT TRIM(INVOICENO)) AS UNIQUE_INVOICES_TRIMMED,
    COUNT(DISTINCT TRIM(STOCKCODE)) AS UNIQUE_STOCK_TRIMMED,
    COUNT(DISTINCT TRIM(DESCRIPTION)) AS UNIQUE_DESC_TRIMMED,
    COUNT(DISTINCT TRIM(COUNTRY)) AS UNIQUE_COUNTRY_TRIMMED
FROM ONLINE_RETAIL_MASTER_TABLE;
