-- INSERT DATA FROM ONLINE_RETAIL1
INSERT INTO ONLINE_RETAIL_MASTER_TABLE(INVOICENO, STOCKCODE, DESCRIPTION,
                                       QUANTITY, INVOICEDATE, UNITPRICE, CUSTOMERID, COUNTRY)
SELECT INVOICENO, STOCKCODE, DESCRIPTION, QUANTITY, INVOICEDATE, UNITPRICE, CUSTOMERID, COUNTRY
FROM ONLINE_RETAIL1;

-- INSERT DATA FROM ONLINE_RETAIL
INSERT INTO ONLINE_RETAIL_MASTER_TABLE(INVOICENO, STOCKCODE, DESCRIPTION,
                                       QUANTITY, INVOICEDATE, UNITPRICE, CUSTOMERID, COUNTRY)
SELECT INVOICENO, STOCKCODE, DESCRIPTION, QUANTITY, INVOICEDATE, UNITPRICE, CUSTOMERID, COUNTRY
FROM ONLINE_RETAIL;

-- CHECK DATA IN MASTER TABLE
SELECT * FROM ONLINE_RETAIL_MASTER_TABLE
LIMIT 10;

SELECT COUNT(*) FROM ONLINE_RETAIL_MASTER_TABLE;