-- ADD YEAR COLUMN TO TABLES
ALTER TABLE ONLINE_RETAIL1
ADD COLUMN YEARS INTEGER;

ALTER TABLE ONLINE_RETAIL
ADD COLUMN YEARS INTEGER;

ALTER TABLE ONLINE_RETAIL_MASTER_TABLE
ADD COLUMN YEARS INTEGER;

-- UPDATE YEAR COLUMN BASED ON INVOICEDATE
UPDATE ONLINE_RETAIL1
SET YEARS = EXTRACT(YEAR FROM INVOICEDATE)::INTEGER;

UPDATE ONLINE_RETAIL
SET YEARS = EXTRACT(YEAR FROM INVOICEDATE)::INTEGER;

UPDATE ONLINE_RETAIL_MASTER_TABLE
SET YEARS = EXTRACT(YEAR FROM INVOICEDATE)::INTEGER;

-- CHECK TOTAL ROWS IN MASTER TABLE
SELECT COUNT(*) FROM ONLINE_RETAIL_MASTER_TABLE;