-- Q1 Identify products with increasing cancellation trends

WITH TOTAL_ORDERS AS (
    -- Total orders per product per year
    SELECT
        DESCRIPTION,
        YEARS,
        COUNT(DISTINCT INVOICENO) AS TOTAL_ORDER
    FROM ONLINE_RETAIL_MASTER_TABLE
    GROUP BY DESCRIPTION, YEARS
),

CANCEL_ORDERS AS (
    -- Total cancelled orders per product per year
    SELECT
        DESCRIPTION,
        YEARS,
        COUNT(DISTINCT INVOICENO) AS CANCELED_ORDER
    FROM ONLINE_RETAIL_MASTER_TABLE
    WHERE INVOICENO LIKE 'C%'  -- cancelled orders
    GROUP BY DESCRIPTION, YEARS
),

CANCELLATION_RATE AS (
    -- Calculate cancellation % per product per year
    SELECT
        T.DESCRIPTION,
        T.YEARS,
        T.TOTAL_ORDER,
        COALESCE(C.CANCELED_ORDER,0) AS CANCELED_ORDER,
        ROUND(
            COALESCE(C.CANCELED_ORDER,0)::NUMERIC / T.TOTAL_ORDER * 100,
            2
        ) AS CANCELATION_PERCENTAGE
    FROM TOTAL_ORDERS T
    LEFT JOIN CANCEL_ORDERS C
        ON T.DESCRIPTION = C.DESCRIPTION
       AND T.YEARS = C.YEARS
    WHERE T.TOTAL_ORDER > 1
),

CANCELLATION_COMPARISON AS (
    -- Compare cancellation rate between consecutive years (YoY)
    SELECT
        E.DESCRIPTION,
        E.CANCELATION_PERCENTAGE AS EARLIER_YEAR_CANCELATION,
        L.CANCELATION_PERCENTAGE AS LATER_YEAR_CANCELATION,
        ROUND(L.CANCELATION_PERCENTAGE - E.CANCELATION_PERCENTAGE, 2) AS RATE_INCREASE
    FROM CANCELLATION_RATE E
    JOIN CANCELLATION_RATE L
        ON E.DESCRIPTION = L.DESCRIPTION
       AND L.YEARS = E.YEARS + 1
)

-- Final result: products with highest increase in cancellation rate
SELECT *
FROM CANCELLATION_COMPARISON
WHERE EARLIER_YEAR_CANCELATION IS NOT NULL
  AND LATER_YEAR_CANCELATION IS NOT NULL
ORDER BY RATE_INCREASE DESC
LIMIT 20;


