
---Find the top 5 countries by total revenue
SELECT 
    COUNTRY,
    SUM(QUANTITY*UNITPRICE)  TOTAL_REVENUE
FROM ONLINE_RETAIL_MASTER_TABLE
GROUP BY COUNTRY
ORDER BY SUM(QUANTITY*UNITPRICE) DESC
LIMIT 5